import { Inter } from 'next/font/google'
import './globals.css'
import ThemeToggle from '@/components/ThemeToggle'
import DisableInspect from '@/components/DisableInspect'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        {/* <div className='bg-white dark:bg-gray-500'>
          <div className='flex justify-end relative'>
            <ThemeToggle />
          </div>
          {children}
        </div> */}
        <DisableInspect />
        <div className='bg-white dark:bg-gray-500 relative'>
          <div className='absolute flex justify-center items-center z-50 w-full'>
            <Navbar />
          </div>
          {children}
          <div className='absolute right-4 bottom-4 z-50'>
            <ThemeToggle/>
          </div>
        </div>
      </body>
    </html>
  )
}
